include:
- template: Dependency-Scanning.gitlab-ci.yml

image: golang:1.14

stages:
- dependencies
- test
- build
- deploy

cache:
  key: yup
  paths:
  - /go/pkg

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_ID
  - if: $CI_COMMIT_BRANCH == "master"

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
  - mkdir -p .go
  cache:
    paths:
    - .go/pkg/mod/

gomod:
  stage: dependencies
  extends: .go-cache
  script:
  - go mod download

lint:
  stage: test
  extends: .go-cache
  image: golangci/golangci-lint:v1.27.0
  script:
  - golangci-lint run -v
  rules:
  - if: $CI_PIPELINE_SOURCE != "schedule"

test:
  stage: test
  extends: .go-cache
  script:
  - go test -race -coverpkg ./... -coverprofile=coverage.txt -covermode=atomic ./...
  after_script:
  - bash <(curl -s https://codecov.io/bash)
  rules:
  - if: $CI_PIPELINE_SOURCE != "schedule"

build:
  stage: build
  extends: .go-cache
  variables:
    CGO_ENABLED: "0"
  script:
  - go build -o keruu
  artifacts:
    paths:
    - keruu
    expire_in: 3 days

publish-site:
  stage: deploy
  image: registry.gitlab.com/lepovirta/lepo-build
  variables:
    NETLIFY_DIRECTORY: public
  before_script:
  - mkdir -p $NETLIFY_DIRECTORY
  script:
  - ./keruu -config lepo-keruu/config.yaml -output $NETLIFY_DIRECTORY/index.html
  - gitlab-deploy-site
  dependencies:
  - build
  rules:
  - if: $CI_COMMIT_BRANCH == "master"
  - if: $CI_MERGE_REQUEST_ID
