aggregation:
  title: Lepo Keruu
  description: Aggregation of interesting posts
  maxPosts: 500

fetch:
  httpTimeout: 10s

feeds:
# People
- name: ane
  url: https://ane.github.io/feed.xml
- name: Brendan Gregg
  url: http://www.brendangregg.com/blog/rss.xml
- name: Cindy Sridharan
  url: https://medium.com/feed/@copyconstruct
- name: Cloud Gardener
  url: https://www.cloudgardener.dev/rss.xml
- name: Cogitations of Topi
  url: http://kettunen.io/index.xml
- name: Dan Luu
  url: https://danluu.com/atom.xml
- name: The Digital Antiquarian
  url: https://www.filfre.net/feed/rss/
- name: Evan Jones
  url: https://www.evanjones.ca/index.rss
- name: Fabien Sanglard
  url: https://fabiensanglard.net/rss.xml
- name: Felix Terkhorn
  url: https://dev.to/feed/terkwood
- name: Henrik Warne
  url: https://henrikwarne.com/feed/
- name: Jessie Frazelle
  url: https://blog.jessfraz.com/index.xml
- name: Juho Snellman
  url: https://www.snellman.net/blog/rss-index.xml
- name: Julia Evans
  url: https://jvns.ca/atom.xml
- name: MS DevOps Dude
  url: https://msdevopsdude.com/atom.xml
- name: rachelbythebay
  url: https://rachelbythebay.com/w/atom.xml
- name: Scott Hanselman
  url: http://feeds.hanselman.com/scotthanselman
- name: Scott's Weblog
  url: http://feeds.scottlowe.org/slowe/content/feed
- name: The Sharp End
  url: https://sharpend.io/feed.xml
- name: Software Arguments
  url: https://medium.com/feed/software-arguments
- name: Stephen Thorne
  url: https://medium.com/feed/@jerub
- name: Steve Yegge
  url: https://medium.com/feed/@steve.yegge
- name: zwischenzugs
  url: https://zwischenzugs.com/feed/

# Companies
- name: Fraktal
  url: https://medium.com/feed/fraktal
- name: Fuzzy Labs
  url: https://medium.com/feed/fuzzylabsai
- name: Gremlin
  url: https://www.gremlin.com/rss.xml
- name: Honeycomb
  url: https://www.honeycomb.io/feed/

# Infrastructure/ops
- name: High Scalability
  url: http://feeds.feedburner.com/HighScalability
- name: SRE Weekly
  url: http://sreweekly.com/feed/

# Programming
- name: GopherSRE
  url: http://www.golangdevops.com/rss/
- name: Lambda the Ultimate
  url: http://lambda-the-ultimate.org/rss.xml

# Software
- name: Windows CLI
  url: https://devblogs.microsoft.com/commandline/feed/

# For testing purposes
- name: Polar Squad
  url: https://medium.com/feed/polarsquad
- name: Lepovirta
  url: https://lepovirta.org/posts/index.xml

